version: "3"

networks:
  canal-test:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    networks:
      - canal-test
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: docker.io/bitnami/kafka:2
    networks:
      - canal-test
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  kafka-consumer:
    image: docker.io/bitnami/kafka:2
    networks:
      - canal-test
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - kafka
    command: kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic example --from-beginning --property print.partition=true

  mysql-upstream:
    image: mysql:5.7
    platform: linux/amd64
    networks:
      - canal-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: ''
    command: --log-bin=mysql-bin --port=3306 --bind-address=0.0.0.0 --binlog-format=ROW --server-id=1 --gtid_mode=ON --enforce-gtid-consistency=true

  mysql-downstream:
    image: mysql:5.7
    platform: linux/amd64
    networks:
      - canal-test
    ports:
      - "4000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: ''
    command: --log-bin=mysql-bin --port=3306 --bind-address=0.0.0.0 --binlog-format=ROW --server-id=1 --gtid_mode=ON --enforce-gtid-consistency=true

  canal:
    image: canal/canal-server
    networks:
      - canal-test
    environment:
      canal.instance.master.address: mysql-upstream:3306
      canal.instance.dbUsername: root
      canal.instance.dbPassword: ''
      canal.mq.topic: example
      canal.serverMode: kafka
      canal.mq.servers: kafka:9092
      canal.mq.flatMessage: true
    depends_on:
      - kafka
      - mysql-upstream
      - kafka-consumer

  canal-adapter:
    # Build from https://github.com/pingcap/tiflow/tree/master/scripts/canal/docker.
    # FIXME: Find a way to make a test image, which is currently in the local magic change.
    image: rustinliu/ticdc-canal-json-adapter:latest
    networks:
      - canal-test
    environment:
      KAFKA_SERVER: kafka:9092
      ZOOKEEPER_SERVER: zookeeper:2181
      # This is actually the name of the topic.
      DB_NAME: example
      DOWNSTREAM_DB_HOST: mysql-downstream
      DOWNSTREAM_DB_PORT: 3306
      USE_FLAT_MESSAGE: true
    depends_on:
      - zookeeper
      - kafka
      - mysql-downstream
